name: Integration Tests

on:
  push:
  pull_request:
    types: [ labeled ]

jobs:
  core:
    if: ${{ github.event.label.name != 'run-fullsuite' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)"
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Test with pytest
      run: |
        # Configure python path for test suite
        chmod +x setup_testing_env.sh
        source ./setup_testing_env.sh
        # Run tests
        pytest -m core --disable-warnings
  
  fullsuite:
    if: ${{ github.event.label.name == 'run-fullsuite' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)"
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Test with pytest
      run: |
        # Configure python path for test suite
        chmod +x setup_testing_env.sh
        source ./setup_testing_env.sh
        # Run tests
        pytest -v -m "not core"
